### ISSUE TITLE
Serilog shown in non-admin account's plugins list

### ISSUE THREAD

**Issue by BuffaloDyl** [Nisaba/btcpayserver-plugin-serilog#1]
Serling is shown in non-admin account's plugins list.  When it is clicked there is a 403 error, but it would be best if the plugin was not shown at all

**Comment by Nisaba** [comment]
ok noted for next release.
Thank you !

**Comment by Nisaba** [comment]
Fixed.
In v1.0.1, the plugin configuration page has moved. It's now under the Server settings page.
